# 5. SQL database: PostgreSQL 9

# 5.1. Installation
- name: Install Postgres on RedHat
  package: "name={{ postgres.name }} state=present"
  notify: restart postgres
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install Postgres on Debian
  apt: pkg={{ postgres.name }} update_cache=yes cache_valid_time=3600
  notify: restart postgres
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# - name: Init Postgres on RedHat
#   command: service postgresql initdb
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install Postgres Java Adapter and Psycog on RedHat
  package: name={{ item }} state=latest
  #apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - "{{ postgres.java_driver }}"
    - "{{ postgres.python_driver }}"
  notify: restart postgres
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install Postgres Java Adapter and Psycog on Debian
  apt: name={{ packages }} cache_valid_time=3600
  vars:
    packages:
    - "{{ postgres.java_driver }}"
    - "{{ postgres.python_driver }}"
  notify: restart postgres
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# 5.2. Database creation and settings
- name: Create DB user
  postgresql_user: name=shibboleth
  become_user: postgres

- name: Create database for Shibboleth on Debian
  become_user: postgres
  postgresql_db: >
    name=shibboleth
    encoding='UTF-8'
    template='template0'
    owner=postgres

- name: Copy tables script
  copy: src="files/tables.sql" dest="/tmp/tables.sql"

- name: Create tables
  become_user: postgres
  shell:  "psql -f /tmp/tables.sql shibboleth"

- name: Enable autovacuum
  replace: >
    dest={{ postgres.conf_path }}/postgresql.conf 
    regexp='#autovacuum_vacuum_scale_factor = 0.2' 
    replace='autovacuum_vacuum_scale_factor = 0.002'

- name: Enable autoanalyze
  replace: >
    dest={{ postgres.conf_path }}/postgresql.conf 
    regexp='#autovacuum_analyze_scale_factor = 0.1' 
    replace='autovacuum_analyze_scale_factor = 0.001'
  notify: restart postgres

# 5.3. Database backup
- name: Create backup directory
  file: >
    path=/var/backups/postgresql 
    state=directory
    owner=postgres
    group=postgres
    mode=0700

# TODO - Add cron job for backups

